[package]
name = "digits"
version = "0.1.0"
edition = "2021"
description = "Hand-written digit recognizer"
authors = [ "Evan McClure <evanmcclure@gmail.com>" ]

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.1"
